#!/bin/sh
source ~/.mtn_settings
echo $REACT_ROOT
if test "$1" == "dew"
then
  if test "$2" == "flux" 
  then
    name=$(node $REACT_ROOT/lib/convert.js $3)
    sed -e "s;%NAME%;$3;g" $REACT_ROOT/lib/dispatcher_template.js  > $REACT_ROOT/app/dispatchers/"$name"_dispatcher.js
    sed -e "s;%NAME%;$3;g" $REACT_ROOT/lib/actions_template.js | sed -e "s;%UNDER%;$name;g" > $REACT_ROOT/app/actions/"$name"_actions.js
    sed -e "s;%NAME%;$3;g" $REACT_ROOT/lib/constants_template.js | sed -e "s;%UNDER%;$name;g" > $REACT_ROOT/app/constants/"$name"_constants.js
    sed -e "s;%NAME%;$3;g" $REACT_ROOT/lib/stores_template.js | sed -e "s;%UNDER%;$name;g" > $REACT_ROOT/app/stores/"$name"_store.js
    tree $REACT_ROOT/app/dispatchers $REACT_ROOT/app/actions $REACT_ROOT/app/constants $REACT_ROOT/app/stores --noreport
   
  fi
  if test "$2" == "react" 
  then
    name=$(node $REACT_ROOT/lib/convert.js $3)
    sed -e "s;%NAME%;$3;g" $REACT_ROOT/lib/component_template.js | sed -e "s;%UNDER%;$name;g" > "$name".js
  fi
  if test "$2" == "future"
    then
    cp $REACT_ROOT/lib/router_template.js  $REACT_ROOT/app/router.js
  fi
fi
if test "$1" == "throwback"
then
  if test "$2" == "flux"
  then
    name=$(node $REACT_ROOT/lib/convert.js $3)
    rm -f $REACT_ROOT/app/dispatchers/"$name"_dispatcher.js
    rm -f $REACT_ROOT/app/actions/"$name"_actions.js
    rm -f $REACT_ROOT/app/constants/"$name"_constants.js
    rm -f $REACT_ROOT/app/stores/"$name"_store.js
  fi
fi
if test "$1" == "install"
  then  
  cp  "${BASH_SOURCE[0]}" /usr/local/bin/mtn
  chmod u+x /usr/local/bin/mtn
fi

